keys:
  - &edger_2022-09-01 age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
  - &edger_host age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *edger_2022-09-01
        - *edger_host
