check-cert-manager:
    echo "https://cert-manager.io/docs/installation/verify/"
    cmctl check api --wait=2m
apply-letsencrypt-staging:
    kubectl apply -f letsencrypt-staging.yaml
apply-letsencrypt-prod:
    kubectl apply -f letsencrypt-prod.yaml
install-cert-manager:
    echo "https://cert-manager.io/docs/installation/"
    kubectl apply -f cert-manager_v1.15.0.yaml
fetch-cert-manager:
    echo "https://cert-manager.io/docs/installation/"
    curl -L https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml > cert-manager_v1.15.0.yaml

