build-and-push-dropbear:
    podman build -t yjpark/dropbear:latest -f dropbear.Dockerfile
    podman push yjpark/dropbear:latest

build-and-push-dropbear-aliyun:
    podman build -t registry.cn-hongkong.aliyuncs.com/yjpark/dropbear:latest -f dropbear.Dockerfile
    podman push registry.cn-hongkong.aliyuncs.com/yjpark/dropbear:latest

