add-displaylink-580:
    # https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu-5.8
    nix-prefetch-url file://$PWD/displaylink-580.zip
add-displaylink-570:
    # https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu-5.7
    nix-prefetch-url file://$PWD/displaylink-570.zip
add-displaylink-561:
    nix-prefetch-url file://$PWD/displaylink-561.zip

