hosts: ENC[AES256_GCM,data:NmJ4OPLzOGVSWXxDVmNMVPkOqw9YdS5Wwyx2hUorszeb+ajhAuwu5JGLe9rS30uH0RYVdlUa5g1URAAnj/OEOjeEPVRVBLZSSgPTO3E9xo20XvvRyaQfgWJ+RcdAp4nCeDCPot9CxkMnpo/riKYsx/A6VFq8jomTku7QhELr0qQMZGn23xjI9gi+VlJ5q2RNr5837hYznP32f3sdyalljG+sjDgGa/fW5fLjDOXR7P84a4RIOWeSrHMExeUGqSEA1VsgiY4N1JGYbLceVkLJnqQqF/jYYgIiFjsyGBwmqH4hdCyIDHE7Z729feMZBl65+oAyLWFR8pYsKn6uVKZOoy5H2/Klt+qtxY8uqeUAg5+lcJbAr8ddMOlQg7EgwczfdqBVS+svhghMlLL0VhvxskpZw96orJT0vIv0yZSR9/4iqSyFgrZ/Y+PT40xgeADiYRV0QYtlZ1JJ2m1zzuSd7KcaQkl8,iv:oVO30wX4ZphwHu8Jevh8Odu5j2Ufo5UhCSs1eGXRpxI=,tag:+3bE191YZp4fWNYV33VmPA==,type:str]
nix-serve.edger.secret: ENC[AES256_GCM,data:08rweN3TEX2sG1MmVcNMF/Fg1XQv48Ae+e8bGCpukiNuPKND/DFFDHYTrgqCnYZ7gvV2dn2YdkNY/SxMctZAf2kGTGzRkqckAtu1mRM6PYVv9VxTRtYGndD93hytrw==,iv:2u4IyD0XYaaGSxnDQQ15H7ZcIX49W5zDyKKLVsnZK90=,tag:z9EvV+jP72zc4b90Wy+Omg==,type:str]
nix-serve.edger.public: ENC[AES256_GCM,data:zit0WOJo6Nou/aKVHcOo8fbvWbO1cQQcwpB2IfPQaTy7hRObOeQqMHXVGQ6QiiTBDLI=,iv:WS6sMMrTJPTSBYmQ+a1A0xgR/O/NK7U5vyt7SRZ+k/I=,tag:u7p5j0ts0YVa7BFO0+71vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dytoMUVHYnFRTmJUcDNr
            Y0x4UlFSOVpFdVN1YWFKbVY4ZWY0NlI5WXk0CmwxTEozeXpQZmFVWTVsY0N4c1po
            MytwZFBnTmZLUEczT2ZubEhzQjlsMWMKLS0tIDhDQlRrRWFCcUpJc2pCZGYwSE83
            T3VEYmtweVVvb01qNTE4TmVIc1VZK0EKLNaAoNhsCAr6b0a9UK+iN6kWDl2Bd6Ml
            TAQF4iXEdBE35s6OXzgfU0YEYq3/yBZfpx57B8iMDv41DOq2nstMyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0FWNWF1OXp2ZGo2c3RU
            WjRITWg4UzdOWDBuOTJiYklQOG9ZV0NQS1RjCk5Kb2dLbTN5dGlSOWFpaVZCSUpM
            cFNKRGtrNC9rWE5xZmhvWHk3ZXpZN3cKLS0tIEJVamxkUEpwTnV1amNKT3pYYi9y
            NXBET1kzQkJaaTk3NVVtdmNoc05lTDAK03xijkctpAvhWlfjYl2aOraFCD2gNNDA
            ODMIPcpnacjaCdUaSe/RzlQXHBTSFVHaE+pLZgaVfmRt8FBUBNH0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T07:32:00Z"
    mac: ENC[AES256_GCM,data:uMOuHN7OIP3o4gzgoKcimcNnlBsVVR9Dp/NAmCfMxtDEMx+3aKLU8QjnUto2I9pS7ym4qXl/MnZCuqHSSsyqkfj8jr4eaha8J6tG9CclmcNjHRWx5L/TamJBEo016zvgV+uf7brViIfZRxvjYyPaoaW0ieBme44BR4lBCie2oJ0=,iv:Ah8o7NAnF/MRnFAFYy6myzTmqGktfTfbcQ7ISbq6FlQ=,tag:G/CeszsfqzXv6wNN0GKJ6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
