hosts: ENC[AES256_GCM,data:W47uLhZ0ui00ECsO2mFwuyAuNxq6rblVh7ZVt6Tt1F1Ck3RDPylXpk9EnE/auE+9iBZGRFFScpfNw/9CmWXV1uD2TImnxMpyfDhmCKwM9AWN0W2nQsyhCoDe6uS7z2hhkQ5vgUxE7jUXwpEQaA6q6qjaqAO3ZrCxN7rXnj7Yu9R85zGwwGjofr3XvY4i3zrwC/b//8qfA2/9N2CVdb0ssE6x0cevV7Frdj9Mz4gukZpmWWOmix1jtdekU7ht0PTe4t5iXv6C0NzvwPmLe14ieH5RZUl8oRjePiwly3os+DZi580pSJSw0HGOfqKhBVM0PhP8w+QyYrnL44cfspPosR9ItX69nYl/IQWYlS5YGwO9cwFPIMGU20zHdCESJfrV+w28FA==,iv:4It1wtdutLfI+VfFQMdsaOiiM/I3zBPVOxhWUJuRUJ4=,tag:ziwPqK3jty8I6MS7QxcKaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dytoMUVHYnFRTmJUcDNr
            Y0x4UlFSOVpFdVN1YWFKbVY4ZWY0NlI5WXk0CmwxTEozeXpQZmFVWTVsY0N4c1po
            MytwZFBnTmZLUEczT2ZubEhzQjlsMWMKLS0tIDhDQlRrRWFCcUpJc2pCZGYwSE83
            T3VEYmtweVVvb01qNTE4TmVIc1VZK0EKLNaAoNhsCAr6b0a9UK+iN6kWDl2Bd6Ml
            TAQF4iXEdBE35s6OXzgfU0YEYq3/yBZfpx57B8iMDv41DOq2nstMyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0FWNWF1OXp2ZGo2c3RU
            WjRITWg4UzdOWDBuOTJiYklQOG9ZV0NQS1RjCk5Kb2dLbTN5dGlSOWFpaVZCSUpM
            cFNKRGtrNC9rWE5xZmhvWHk3ZXpZN3cKLS0tIEJVamxkUEpwTnV1amNKT3pYYi9y
            NXBET1kzQkJaaTk3NVVtdmNoc05lTDAK03xijkctpAvhWlfjYl2aOraFCD2gNNDA
            ODMIPcpnacjaCdUaSe/RzlQXHBTSFVHaE+pLZgaVfmRt8FBUBNH0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T03:45:48Z"
    mac: ENC[AES256_GCM,data:XbUMvUs1agPLeCOr9wsbhKpr7Bx+Uac7QJeH5jzkW/+ToAGenflsVFQ3XhKhwxFEBax5PZaDvjrUcy785d0rH1DfD6Q6P99X1k4C2a2lybc2w6zXuE1lDvufoGQcqBbt2TwgmQkqeAuhh39ZMZzgnIicqw/+QF3wE9ruKWaifaM=,iv:oPqrmUp8pkTs71EdOM1cH8UUfst7/eWmTFNyOWGr/Qg=,tag:b6GrA4gl0K6C9CSVIRZjeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
