hosts: ENC[AES256_GCM,data:W0njHcbjVpcS4Sdil1uaAH/HKTwcWN9zwLA0CC29BQFZfQ6+YAk2CN99m0WF7Db7b/kf83ub43L/nISNbuPNmFsbjZXRzblhCArp60NuoR1w3fb1WTigYgILVru3tbK001Cfphvo5YfjwW5dgUl3+P5Rjefh8sb+vdaKexQIWzV9933ZuOxWXHfdI+xR9D46JbB3khlWmGk+CkOEUxnE8NNhCIGl1kyqDOnx47U0pW5G4/H4QUmNWNmD177C4/lnI+R1o7v3/ObV5AtNQA/n8w+E0GQvHPUtRkOi7PKjeRmaMqDc6q2ABOzNNEcx7cn7yQwxSwC+1dwBzX8KO8/koKh2FYaZ8Jjps85KBJIhtf/+uFmyRyXnYv1mLKhkTD23jErm3kY8wUfXqaUQfGAiLLCUBz5hohyyKhsxAN/IJF0ENplxODXHZAFMDLr+qNS3pfK8B9g0VZ//8Q04/blxpTKeCWMjiXpRyK5TK3zd9LP6MoUbFs1psH0SikdjXt8k4jn5iS3AJof+,iv:GKhRgR2DlMgwZAb2B5DuCvNdLNyncVAYj1Q5FJdQgj8=,tag:XopcFgZp+uDep9nwp6N8Ww==,type:str]
nix-serve.edger.secret: ENC[AES256_GCM,data:08rweN3TEX2sG1MmVcNMF/Fg1XQv48Ae+e8bGCpukiNuPKND/DFFDHYTrgqCnYZ7gvV2dn2YdkNY/SxMctZAf2kGTGzRkqckAtu1mRM6PYVv9VxTRtYGndD93hytrw==,iv:2u4IyD0XYaaGSxnDQQ15H7ZcIX49W5zDyKKLVsnZK90=,tag:z9EvV+jP72zc4b90Wy+Omg==,type:str]
nix-serve.edger.public: ENC[AES256_GCM,data:zit0WOJo6Nou/aKVHcOo8fbvWbO1cQQcwpB2IfPQaTy7hRObOeQqMHXVGQ6QiiTBDLI=,iv:WS6sMMrTJPTSBYmQ+a1A0xgR/O/NK7U5vyt7SRZ+k/I=,tag:u7p5j0ts0YVa7BFO0+71vg==,type:str]
nix-serve.a13.secret: ENC[AES256_GCM,data:znwsxjUv+pjb/QP2U7qQ2ZZ8WL3bOoRV0mu1XndxHA7wNX3msBXShg2jOUclLFn0QUOz5jPMU3or5dn2O7qffT2y4UaKnnqLM5n2i3vq/0qA2zsRhPqFat9xbwA=,iv:CgaGJaOz2sWB4TEvGuMSZimYb8OHzgQaYv7FqeJ5SKE=,tag:Fnv4QTpY/STrXxT0O97Dcw==,type:str]
nix-serve.a13.public: ENC[AES256_GCM,data:CEb0ICw5laBkS5ZiP9mzRFjpV1wbUDPRjQQRqjg1O2wWq7ypjY8jMsWHx3ETlKkT,iv:8Tz1RNciKsUx/iV5ozr5tnRly5DjSL4VrC6LQjWZ4Jk=,tag:DvOomM9/4yMrC9Ux4rKhLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueGZlcm9TbFJYQTRFeU92
            b1U3NmRYYjlGb2lpTm43RkZlQmpWSXNKZUE0Cjc1QnVIVk9qZ1NsT2NIR3RYRXl0
            Q1dDaGFGSFNEV1dUTDFmb2tZeGZHODAKLS0tIG9CUmlEM2tVaW43OGZHWmNBbE1S
            alM5RVlJdDNRRExhUjlxWTdXQ09Ya00KMzxgdPWrpAJGNT3TtWfcUPDmHSTuUSs/
            ipIk542su9YsEczYfYSuqj4BRvCBNGM1qUVn1qxjBb98/udzp35WvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaUlRQTNVTUY3Q0gwZmVa
            L2M5bUR6UitMdUgvMWY1SllHdHFHRGZpNTA0CkVscnZRVmg0OXl2Zm5BdGc2SnVs
            TjQxanJHR1dsRjNGdXNDbngxbzQ4ZTQKLS0tIG0rSXRudmtycm5MNTQvWUI1bUVx
            Z21ZUkRZVzV5bk9EWW83UUNkUXh4bmcKGwf7W4ZkkQfCGAJMW+T2aE4G9QLiEsiq
            gE8oa3a566ccO8vIiY9v3MFHcb0EqpeKavBxV/NpvFmTqezWr/+37w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acawzy46wfd98qrx93yrafyeqn3etg6s7k4z5t59mm7vjh5eyf9ssr7sh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWGVvY0RWeE9LU2g4ZzNO
            K2luZk4xSlpMMHZHVThUQ29FWDF5Q0x1TUNNCmVISHVHdUFtdkFSbFJ5YUFQZDNt
            UzE4ejg2Z3BEdjBkZlQ2UWx6WXR4NzAKLS0tIGFtZHdHR3pHSnROUUVEbVNPL2kx
            T2l5Um1wVTdLOGtoQlJZcTZSbm5lKzAK0C5cUYG0+Tdw8olr0bAyQD9HPde8LCku
            LRzXbdlwhqxXFFiqevCbeGZQ/lIt3IVw6qW8o7g6GCTm5ACA2nROiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kndmmujxnm43k85grj9qajpyx4k7l47crf7fd66ez56nn4u5rp5qdmwu8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR3FiT0kwN0YrQzI5a095
            VjloRmpEbitVOUxyMUNZeHhLOXlYK0pJMld3CnJudzM4dnAvMDFtQmJGbVRxMC94
            T3BPbXB0aTF4bmg2UTNWWUpBOUd6R2MKLS0tIE5lVjE4SWc5K1BRK1Zuc3kyMmsw
            WEsxMWlSK0hUUnhKRzF3cmlUdnljb0EKv1uHdz/enr1FTQJeilbGS3qnXt5LErtr
            gEEzHYLk3GpE9H9e2yqb5Jel6Vwnow93Lz4xNiAkppBTDbeU9koN9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zmywzjh8j4h6macx7nh3csxjja3umm07wjq92v7g3dgfs6jhmefqeahpdr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXV4aDE3VkdBd2ZrRU14
            YXE3aTJuRVI2bXFtRHNUb0VEOThhdVZjK2tJCnduZ05OenFkVmVTS0lkRm1KNHBG
            S09IYVhUMW9XbHJaMGdYSW5Ec0NrUWsKLS0tIEtWQUpIUElrblZaeXh0ZEdBTFpi
            SkMrMm5jTWcrcVEzN0x0QjZFNzNXYlEKoJn7AgBrdBb9SiXLTa3xJQ+CvgCdpxrl
            v5RMKMSpGIpY+mYzsYVpF6AVDlItQxGaoJRY+fk8OlMWpUYjd91ycg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ygyut4r4gs2gdt4hjnpmpggmz8xmv5ypqmjcfrqy98wd4hm53emsycsazq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaDNrSkpjeWZQUEtHZkE3
            cFZKS2hCT0Z1ZUZ5WUR3SVFCd0RjVDgrTWdnCnZMeTBxVHZNdUZHa0JkQ09UMjJu
            Ny94azFoVDdnYlhsQ3VXV09PRXZUR0UKLS0tIHBCMDB6dDNIMXhlUk85MUdFUkFX
            eUF6K3JTa0paNFhqV2RKelp4NUNYVzgKnalAvvvnT7xLa6MBlUMFQ2vBWQeEpuCB
            ajoIdbr5iByQWGYqqt+njn5FiVEx9wD7etcvOA3Y6GNi+SExCgZpJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T05:57:34Z"
    mac: ENC[AES256_GCM,data:ZVsRADh3stOkP42Y2FSPXcMfyCR4RyJRErLFB5GiytufVTeT25sTIXoLOvJM3cHX6RBDF97am3jpoVNMpbFZ9z7hzGCcjRkGFs6bNJP1QV7ZoOKABKG/TxdGWJTel50ogFeAoJyYqc1nrbvwdaxEAYZxmqJAksl05HzyfHXXbTM=,iv:yPQR0EGWCb9NF2pj2M0MunwUJTqmSz6c297rodBXApM=,tag:pdbSHwrKPWgC6bQ00J2hUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
