hosts: ENC[AES256_GCM,data:NmJ4OPLzOGVSWXxDVmNMVPkOqw9YdS5Wwyx2hUorszeb+ajhAuwu5JGLe9rS30uH0RYVdlUa5g1URAAnj/OEOjeEPVRVBLZSSgPTO3E9xo20XvvRyaQfgWJ+RcdAp4nCeDCPot9CxkMnpo/riKYsx/A6VFq8jomTku7QhELr0qQMZGn23xjI9gi+VlJ5q2RNr5837hYznP32f3sdyalljG+sjDgGa/fW5fLjDOXR7P84a4RIOWeSrHMExeUGqSEA1VsgiY4N1JGYbLceVkLJnqQqF/jYYgIiFjsyGBwmqH4hdCyIDHE7Z729feMZBl65+oAyLWFR8pYsKn6uVKZOoy5H2/Klt+qtxY8uqeUAg5+lcJbAr8ddMOlQg7EgwczfdqBVS+svhghMlLL0VhvxskpZw96orJT0vIv0yZSR9/4iqSyFgrZ/Y+PT40xgeADiYRV0QYtlZ1JJ2m1zzuSd7KcaQkl8,iv:oVO30wX4ZphwHu8Jevh8Odu5j2Ufo5UhCSs1eGXRpxI=,tag:+3bE191YZp4fWNYV33VmPA==,type:str]
nix-serve.edger.secret: ENC[AES256_GCM,data:08rweN3TEX2sG1MmVcNMF/Fg1XQv48Ae+e8bGCpukiNuPKND/DFFDHYTrgqCnYZ7gvV2dn2YdkNY/SxMctZAf2kGTGzRkqckAtu1mRM6PYVv9VxTRtYGndD93hytrw==,iv:2u4IyD0XYaaGSxnDQQ15H7ZcIX49W5zDyKKLVsnZK90=,tag:z9EvV+jP72zc4b90Wy+Omg==,type:str]
nix-serve.edger.public: ENC[AES256_GCM,data:zit0WOJo6Nou/aKVHcOo8fbvWbO1cQQcwpB2IfPQaTy7hRObOeQqMHXVGQ6QiiTBDLI=,iv:WS6sMMrTJPTSBYmQ+a1A0xgR/O/NK7U5vyt7SRZ+k/I=,tag:u7p5j0ts0YVa7BFO0+71vg==,type:str]
nix-serve.a13.secret: ENC[AES256_GCM,data:znwsxjUv+pjb/QP2U7qQ2ZZ8WL3bOoRV0mu1XndxHA7wNX3msBXShg2jOUclLFn0QUOz5jPMU3or5dn2O7qffT2y4UaKnnqLM5n2i3vq/0qA2zsRhPqFat9xbwA=,iv:CgaGJaOz2sWB4TEvGuMSZimYb8OHzgQaYv7FqeJ5SKE=,tag:Fnv4QTpY/STrXxT0O97Dcw==,type:str]
nix-serve.a13.public: ENC[AES256_GCM,data:CEb0ICw5laBkS5ZiP9mzRFjpV1wbUDPRjQQRqjg1O2wWq7ypjY8jMsWHx3ETlKkT,iv:8Tz1RNciKsUx/iV5ozr5tnRly5DjSL4VrC6LQjWZ4Jk=,tag:DvOomM9/4yMrC9Ux4rKhLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dnJBVzY0cmJQcmI3eEQ3
            OWN1N3F0ckpIT3p1T3l6Ump5bkVwSTFpLzJBCjdCbGtnYTBrbU1hWk9MOXhxTE9h
            MlZ1SERwK282alhYSEVucllpV1pCL2MKLS0tIHM5ODVmT0lHN3hRUDduQVJCNDNM
            VkEraVhGbFpaSEEySFZYMnNBcXZnK0EKv9KIS1FFk5hfDztrPzJZBVAHDvNmXRwD
            Hb/HvcmhITW7+Xp6mRz/40oX0ck34x5FeYDuhTS+16ikUsMOLr4Wsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZWUwSmNwYU9VYW1LKy9t
            T2ttZ2ViWnhmcGQ1eFJ4UVhUT0dhanFKWlIwCjJIcFlhZWRQelRZRUVaR1gyaUor
            eHJwTlpkZ3grdnAzbm1OMGtOK1o5RmcKLS0tIEoySGpwTzdIQzB6LzRNS3Ixam1Z
            RU1lNFdGVXlPQVF2ZHBHaDlLUy9hVU0KLbpdL/76jymwUUOenpYqkRTQwoxLLqLC
            Ls/jQ1TxsTfTXkKywvFnslKm8N1uFJzeC3a4OiEAMHcn8gmDt7R1uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acawzy46wfd98qrx93yrafyeqn3etg6s7k4z5t59mm7vjh5eyf9ssr7sh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnE5UHRiMEhtRkQyVTBD
            RzJIZ0p6WkZUY1Q3UFN1clY4MmVlYU15aWlnClZKWG1XTFdrY3c2aXhoVDdWVUo4
            STc4UDRTU3lNL1JiZDRmcnUzbHNCMzAKLS0tIEVxS3N5NGgxaER6dEtIRUhkZXpG
            TDJJOVFTSW8rbG53cEZ1Q1lQZDdBQzAKFFwrSVyV8o8WJY1D5LItGW5046e03nw7
            YFN8ePRitatMGKpqsh8xAyJ4g/2nSSQFP1kyF7UG7/f7tt4HluPGQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zmywzjh8j4h6macx7nh3csxjja3umm07wjq92v7g3dgfs6jhmefqeahpdr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZXh5SGtQM2dIbElQZkk2
            UTdLdnk4cWVoblJJVzE1cXNReXNkNzFscXprCnZnUGkzVHBOdEp6Q3gvR3VPWnpR
            NS9xSHRSRHRBMFhlZXNGdHFqR204RkEKLS0tIC94V0JrQVRRaC9uR3NpOGZhREcr
            K1NRUlZ0bWRPckwzSUhOaU1QUEl6N28K6G9XifzzlxzuNW6ZiUqhHes6HEuiN91g
            AkVn26ndDEJuzatm7Z8u1EEoaNv49+owuiZuBLAzX2ZMfvfZg32UAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ygyut4r4gs2gdt4hjnpmpggmz8xmv5ypqmjcfrqy98wd4hm53emsycsazq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N0pLOEFrbVd2TlpRSitR
            OWhKYy90OFN5bnhaT216UUVXeHBUWVVYZVRRClI5N01ZWDJPN0hkWC9JU091NmRR
            UWFmdm9QcjlkR24rTGwxVm0wTTBKNE0KLS0tIGJKQXFKQkI0c2g0TnpHejVNckFN
            eWZyOCtYYk9jWkMvTTRsbVV2eWx4dDgKOFY8WaxSgpd2yViNPwUIiR1jPY30C76j
            ALimQGHJ4a4/KO9xGTxcH+IjRK2+vShxZNp9C/BJ6mTGYMqIbTFJBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-08T07:21:13Z"
    mac: ENC[AES256_GCM,data:HUH9wFmj8tsXprWn8kBAv1qB+qQhlsDwXKPQ9Cn9U9eG9B/slpqkl6vF5SdjoJT7zEp/6fF2pFCr5B2pDxRi0cs1NBkqJfeDJOJO49aKz1hzcGh2L+w4sq8j6ltZRzIdLyibPLiTPLZVEcbDViWyW5ExymkeaInOGBUjU4/hvQo=,iv:kHhA+IOYDWpkiHsYW1rriUWK3LNEicV0nTTZAAQYSog=,tag:oPkLYKF57yNIiEEOuUCGrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
