hosts: ENC[AES256_GCM,data:KPHX77SZpN1p+qtxpalZswk5vto3Cl4lhO8kayw6WSgOZu+E3CJJbtHK+29LbxyxNa/2827M7IDhLd1nyEpxkRO9IXgPEG+jY7lX4/s4WV6hKhPMPes98cQljgWg8qir0u4Jv5sIR4IOb+TbZKxFo5Wq992Bo7Ho+h0YuOhiVX/Kblz7I/f8DhJT/cGjNwnthrAwtrA29MVEubZpSV0J/LA1OesDYcXQSaxPyAiMGNnKQA5fu7GkehmjRfwKr6KF5vzLoOTAQq/soDJIKmlxrLCZ1816EMAfqrVlh9s3tztQJkfFyEOJL5DNnjNErRYacNn5hUuJXTFP7PLgF/r68VD+lvGaskjC32tp,iv:qV2KhVDOmSRdk9URkj8xC+MV9/9nP8jv/1eId5QfPxQ=,tag:mG7yaN16cmjVMpMK+SJA2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dytoMUVHYnFRTmJUcDNr
            Y0x4UlFSOVpFdVN1YWFKbVY4ZWY0NlI5WXk0CmwxTEozeXpQZmFVWTVsY0N4c1po
            MytwZFBnTmZLUEczT2ZubEhzQjlsMWMKLS0tIDhDQlRrRWFCcUpJc2pCZGYwSE83
            T3VEYmtweVVvb01qNTE4TmVIc1VZK0EKLNaAoNhsCAr6b0a9UK+iN6kWDl2Bd6Ml
            TAQF4iXEdBE35s6OXzgfU0YEYq3/yBZfpx57B8iMDv41DOq2nstMyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hkj94767mumelqr7qwa0c589mq9fenqj0z9g0n948aprrul7evseffxk4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0FWNWF1OXp2ZGo2c3RU
            WjRITWg4UzdOWDBuOTJiYklQOG9ZV0NQS1RjCk5Kb2dLbTN5dGlSOWFpaVZCSUpM
            cFNKRGtrNC9rWE5xZmhvWHk3ZXpZN3cKLS0tIEJVamxkUEpwTnV1amNKT3pYYi9y
            NXBET1kzQkJaaTk3NVVtdmNoc05lTDAK03xijkctpAvhWlfjYl2aOraFCD2gNNDA
            ODMIPcpnacjaCdUaSe/RzlQXHBTSFVHaE+pLZgaVfmRt8FBUBNH0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T15:36:34Z"
    mac: ENC[AES256_GCM,data:BVAE7lUwXGSu8311EEttTOwFQ5qYpq1wMUpY4yNm8C48zj9A6TzASoQywezZQr2h7DRB28QM/buIg8tIx9GQVsmK7xv7t8KIomk+pKH8tJGXtdKQD1/VyV6s0HsEWdqsCtQXQaJqbLNv7rEWLnzDrXWdbEWYHPKXLK5zxUK/Pqc=,iv:IyeUrDP6FK8Cv3LoPe2Dw0QZ91iMHfmmWqMpJxo6ehU=,tag:gCkaDiX5V6lu5WDh2UJYVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
